package com.rpglab.game.battle.moves;

import com.rpglab.game.interfaces.CombatAction;
import com.rpglab.game.interfaces.Combatente;

/**
 * An intimidating roar attack that damages enemies through fear and sonic force.
 * This combat action uses vocal intimidation and sound waves to harm
 * the target psychologically and physically through overwhelming presence.
 * 
 * <p>This move is typically used by large, predatory monsters such as
 * dragons and other apex predators to assert dominance and inflict
 * damage through sheer intimidation.</p>
 * 
 * @author quimberlyia and gaamelu
 * @version 1.0
 * @since 1.0
 */
public class Roar implements CombatAction {
    
    /**
     * Executes the intimidating roar attack on the specified target.
     * The attack deals 25 points of psychological damage, representing
     * the overwhelming fear and sonic force generated by a powerful roar.
     * 
     * @param user   the combatant performing the roar (typically large predators)
     * @param target the combatant receiving the intimidation damage
     */
    @Override
    public void execute(Combatente user, Combatente target) {
        int damage = 25; // Intimidating roar damage
        target.takeDamage(damage);
        System.out.println(user.getName() + " used roar on " + target.getName() + " dealing " + damage + " damage!");
    }
}
